apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
  labels:
    env: production
spec:
  type: NodePort
  selector:
    type: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
      protocol: TCP