apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
  - apiGroups: ["","apps"]
    resources: ["pods","deployments"]
    verbs: ["get","watch","list","create","delete"]