apiVersion: v1
kind: Deployment
metadata:
  name: affinity-rule
  labels:
    app: production
spec:
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
        - name: frontend
          image: nginx
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: production
                topologyKey: "kubernetes.io/hostname"
              weight: 100