apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    env: production
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  replicas: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80