apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: my-app-container
    image: my-app-image:latest
    startupProbe:
      httpGet:
        path: /healthz  
        port: 8080      
      initialDelaySeconds: 10 
      periodSeconds: 5   
      failureThreshold: 12  
      timeoutSeconds: 2  